blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    #apps
    path('', include('core.urls')),
    path('',include('usuario.urls')),
    path('',include('posts.urls'))
]
if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import index
from core.views import contato


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('contato',contato,name='contato'),
    
]

posts/urls.py
from django.urls import path
from posts.views import PostListView, PostCreateView, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('posts',PostListView.as_view() ,name='posts_blog'),
    path('criarpost', PostCreateView.as_view(), name='criar_posts'),
    path('posts/<int:pk>/apagar', PostDeleteView.as_view(), name = 'apagar_post'),
    path('posts/<int:pk>/editar', PostUpdateView.as_view(), name= 'editar_post'),
]

usuario/urls.py
from django.urls import path
from usuario.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView, UserDetailView, UserLoginView, UserLogoutView
app_name = 'usuario'

urlpatterns = [
    path('usuario',UserListView.as_view() ,name='listar_usuarios'),
    path('criarusuario', UserCreateView.as_view(), name='criar_usuario'),
    path('usuario/<int:pk>/editar', UserUpdateView.as_view(), name= 'editar_usuario'),
    path('usuario/<int:pk>/apagar', UserDeleteView.as_view(),name= 'apagar_usuario'),
    path('usuario/<int:pk>/detalhes', UserDetailView.as_view(), name= 'detalhes_usuario'),
    path('loginusuario', UserLoginView.as_view(), name = 'login_usuario'),
    path('logoutusuario', UserLogoutView.as_view(), name = 'logout_usuario'),
]

core/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from usuario.models import User

class Posts(models.Model):
    autor = models.ForeignKey(User,on_delete= models.CASCADE, verbose_name='autor', related_name='post')        
    text = models.TextField(unique=False)
    date = models.DateTimeField(auto_now_add=True)
    imagem = models.ImageField(upload_to='posts/', blank=True, null=True )
    
    

    def __str__(self):
        return f'Autor: {self.autor} | Data: {self.date} | id: {self.id}'

usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
   
# Create your models here.

posts/forms.py
from posts.models import Posts
from django import forms

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['autor', 'text', 'imagem']

usuario/forms.py
from usuario.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']

core/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context={
        'pj':'poli junior',
    }

    return render(request, 'core/index.html', context)

def contato(request):
    context={
        'pj': 'poli junior',
        'ano':2020,
    }
    
    return render(request, 'core/contato.html', context)
    

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.views import generic
from posts.models import Posts
from django.urls import reverse_lazy
from posts.forms import CreatePostForm
from django.contrib.auth.mixins import LoginRequiredMixin

class PostListView(ListView):
    model = Posts
    context_object_name = 'posts'
    template_name = 'Postt/post.html'
    
class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Posts
    template_name = 'Postt/createpost.html'
    form_class = CreatePostForm
    success_url = reverse_lazy('posts:posts_blog')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Posts
    template_name = 'Postt/apagarpost.html'
    context_object_name = 'posts'
    success_url = reverse_lazy('posts:posts_blog')

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Posts
    template_name = 'Postt/editarpost.html'
    fields = ['text', 'imagem']
    success_url = reverse_lazy('posts:posts_blog')

usuario/views.py
from django.shortcuts import render
from usuario.models import User
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from usuario.forms import CreateUserForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

class UserListView(ListView):
    model = User
    context_object_name = 'users'
    template_name = 'Usuario/usuario.html'

class UserCreateView(CreateView):
    model = User
    template_name = 'Usuario/create.html'
    form_class = CreateUserForm
    success_url = reverse_lazy('usuario:listar_usuarios')

class UserUpdateView(UpdateView):
    model = User
    template_name = 'Usuario/editarusuario.html'
    fields = ['username', 'email','password']
    success_url = reverse_lazy('usuario:listar_usuarios')
    
class UserDeleteView(DeleteView):
    model= User
    template_name = 'Usuario/apagarusuario.html'
    context_object_name = 'usuario'
    success_url = reverse_lazy('usuario:listar_usuarios')

class UserDetailView(DetailView):
    model = User
    template_name = 'Usuario/detalhesusuario.html'
    context_object_name = 'users'

class UserLoginView(LoginView):    
    template_name = "Usuario/loginusuario.html"


class UserLogoutView(LoginRequiredMixin, LogoutView):
    pass

templates/Postt/apagarpost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        
        #formapagar{
            border: 2px solid black;
            background-color: red;
            padding: 5px;
            width: min-content;
            color: black;
            align-items: center;
        }
            </style>
</head>
<body>
    <h1>Voce deseja realmente apagar o post</h1>
    <form id="formapagar"action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Apagar">
    </form>
</body>
</html>

templates/Postt/createpost.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Criar postagem</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{% render_field form.autor %}</p>
        <p>{% render_field form.text %}</p>
        <p>{% render_field form.imagem %}</p>
        <input type="submit" value="Enviar">
    </form>
</body>
</html>

templates/Postt/editarpost.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Edite seu post</h1>
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Texto:{% render_field form.text %}</p>
    <p>Foto:{% render_field form.imagem %}</p>
    <input type="submit" value="Editar">
    </form>
</body>
</html>

templates/Postt/post.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        #posts {
            border: 1px solid black;
            padding: 10px;
        }
        #navbar{
            border: 2px solid black;
        }
        body{
            margin:0;
            padding: 0;
        }
    </style>
</head>

<body>
    <div id="navbar">
        {% if not request.user.is_authenticated %}
        <ul>
            <li> <a href="{% url 'usuario:login_usuario' %}">Login</a></li>
            <li> <a href="{% url 'usuario:criar_usuario' %}">SingUp</a></li>
        {% else %}
            <li> Olá, <a href="{% url 'usuario:detalhes_usuario' request.user.id %}"> {{request.user.username}}</a></li>
            <li> <a href="{% url 'usuario:logout_usuario' %}"> Logout</a></li>
        {% endif %}
        </ul>
    </div>
    <h1>POSTS</h1>
    {%  for x in posts%}
    <div id="posts">

        <div>{{x.autor}}</div>
        <div>{{x.text}}</div>
        <div>{{x.date}}</div>
        {% if x.imagem %}
        <img src="{{x.imagem.url}}">
        {% else %} 
          <div>Nao tem imagem</div>    
        {% endif %}
    

        <a href="http://localhost:8000/posts/{{x.id}}/apagar">
            <button>Apagar post</button>
        </a>
        <a href="http://localhost:8000/posts/{{x.id}}/editar">
            <button>Editar post</button>

        </a>
    </div>
    {% endfor %}
    <div>
        <a href="http://localhost:8000/criarpost">
            <button> Criar post</button>
        </a>
    </div>
</body>

</html>

templates/Usuario/apagarusuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>

#formapagar{
    border: 2px solid black;
    background-color: red;
    padding: 5px;
    width: min-content;
    color: black;
    align-items: center;
}
    </style>
</head>
<body>
    <h1>Voce deseja realmente apagar o usuario</h1>
    <form  id="formapagar" action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Apagar">
        </form>
</body>
</html>

templates/Usuario/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        
        #formcriar{
            border: 2px solid black;
            background-color: red;
            padding: 5px;
            width: min-content;
            color: black;
            align-items: center;
        }
            </style>
</head>
<body>
    <h1>Criar usuario</h1>
    <form id="formcriar" action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Enviar">
    </form>
</body>
</html>

templates/Usuario/detalhesusuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Detalhes do Usuario</h1>
    
    <div>
        <div>Olá,{{user.username}}</div>
        <div>{{user.email}}</div>
        <div>Suas postagens:</div>
        {% for post in users.post.all %}
            {% if post.imagem %}
            <img src="{{post.imagem.url}}" alt="">
            {% else %}
            <div>nao tem imagem</div>
            {% endif %}
        {% endfor %}
    </div>
    
</body>
</html>

templates/Usuario/editarusuario.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        
        #formeditar{
            border: 2px solid black;
            background-color: red;
            padding: 5px;
            width: min-content;
            color: black;
            align-items: center;
        }
            </style>
</head>
<body>
    <h1>Edite seu usuario</h1>
    <form id = "formeditar" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Nome:{% render_field form.username %}</p>
    <p>Email:{% render_field form.email %}</p>
    <p>Senha:{% render_field form.password %}</p>
    <input type="submit" value="Editar">
    </formi>
</body>
</html>

templates/Usuario/loginusuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    LOGAR
    <form method="post"action="">
        {% csrf_token %}
        {{form.as_p}}

    <input type="submit" value="Logar">
    </form>
</body>
</html>

templates/Usuario/usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
#user{
    border: 2px solid black;
    padding: 10px;
    width: min-content;
    margin-top:30px;
    background-color: limegreen;
    
}
body{
    display: flex;
    justify-content: space-around;
    flex-direction: column;
    
    align-items: center;
}
#criar{
    margin-top: 30px;
}
    </style>
</head>
<body>

    <h1>USUARIOS</h1>
    
    {% for user in users%}
    <div id="user">

    <div>{{user.username}}</div>
    <div>{{user.created_at}}</div>
    <a href="http://localhost:8000/usuario/{{user.id}}/editar">
    <button>
        EDITE O USUSARIO
    </button></a>
    <a href="http://localhost:8000/usuario/{{user.id}}/apagar">
        <button>
            APAGUE O USUSARIO
        </button></a>
    <a href="http://localhost:8000/usuario/{{user.id}}/detalhes">
        <button>
            DETALHES DO USUARIO
        </button>
    </a>
</div>
{% endfor %}
<div id="criar">
    <a href="http://localhost:8000/criarusuario">
    <button>CRIAR USUARIO</button>
    </a>
</div>
</body>
</html>

templates/core/contato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'core:index' %}">INDEX</a>
    <h2>LISTA DE CONTATOS</h2>
    {{pj}}
    {{ano}}
</body>
</html>

templates/core/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
#index{
    display: flex;
    justify-content: space-around;
    flex-direction: column;
}        
    </style>
</head>
<body>
    <div id="index">
    <a href="{% url 'core:contato' %}">CONTATO</a>
    <a href="http://localhost:8000/posts">POSTS</a>
    {{pj}}
    </div>
</body>
</html>